# Generated by Django 6.1.1 on 2026-09-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
    ]
