# Generated by Django 6.1.1 on 2026-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_topic_title_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
