# Generated by Django 6.1.1 on 2026-09-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_subtopic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
