# Generated by Django 6.1.1 on 2026-09-06 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_subtopic_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='content',
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.course'),
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_example', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('snippet', models.TextField()),
                ('expected_answer', models.CharField(max_length=256)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.subtopic')),
            ],
        ),
    ]
