# Generated by Django 6.1.1 on 2026-09-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_remove_subtopic_content_alter_subtopic_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillBlankQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=64)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='SelectOptionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=256)),
                ('options', models.JSONField(blank=True, default=list)),
                ('anser', models.IntegerField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=256)),
                ('answer', models.BooleanField()),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.subtopic')),
            ],
        ),
    ]
