# Generated by Django 6.1.1 on 2026-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_fillblankquiz_selectoptionquiz_truefalsequiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectoptionquiz',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='truefalsequiz',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='codes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='quizzes',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='FillBlankQuiz',
        ),
        migrations.DeleteModel(
            name='SelectOptionQuiz',
        ),
        migrations.DeleteModel(
            name='TrueFalseQuiz',
        ),
    ]
