# Generated by Django 6.1.1 on 2026-09-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_remove_selectoptionquiz_subtopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='codes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='quizzes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
